<a href="https://colab.research.google.com/github/mohammedirfan78698/AIML-25_B15/blob/main/Lab2_15_1997.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
marks = np.array([[85, 78, 92],[70, 88, 84],[90, 95, 94],[60, 65, 70],[82, 79, 85]])
print(marks)


[[85 78 92]
 [70 88 84]
 [90 95 94]
 [60 65 70]
 [82 79 85]]


In [39]:
average_marks = np.mean(marks)
print(average_marks)
min_marks = np.min(marks)
print(min_marks)
max_marks = np.max(marks)
print(max_marks)

81.13333333333334
60
95


In [40]:
specific_students = marks[[0, 2]]
print(specific_students)

[[85 78 92]
 [90 95 94]]


In [41]:
print("Marks above 80:",marks[marks > 80])


Marks above 80: [85 92 88 84 90 95 94 82 85]


In [42]:
subject=marks.T
print(subject)

[[85 70 90 60 82]
 [78 88 95 65 79]
 [92 84 94 70 85]]
